# Default values for cpd-install-pipeline.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# specify ppc64le or s390x, empty is x86 (default)
arch: "x86"

tektonPatch:
  enabled: true
  defaultTimeoutMinutes: 300
  activateEnum: true
  tektonNamespace: openshift-pipelines