# Default values for cpd-install-pipeline.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# specify ppc64le or s390x, empty is x86 (default)
arch: "x86"

# default olm utils image to use
default_olm_utils_image: "icr.io/cpopen/cpd/olm-utils-v3"

# Cloudpak for Data / OLM version to set as default in pipelines
cpd_version: "5.2.1"

# Cloud pak for Data mode to set as default in pipelines: cpd-enterprise, watsonx
default_cpd_install: "watsonx"

storageClass:
  block: ocs-storagecluster-ceph-rbd
  file: ocs-storagecluster-cephfs

# Proxy configuration
proxy:
  enabled: false
  http_proxy: http://user:password@IP:port
  https_proxy: http://user:password@IP:port
  no_proxy: "localhost,127.0.0.1,.svc,.cluster.local"

# Private registry docker secret for disconnected (airgap) installation
airgap:
  enabled: true
  private_registry_secret: "private-registry-secret"

tektonPatch:
  enabled: true
  defaultTimeoutMinutes: 300
  activateEnum: false
  tektonNamespace: openshift-pipelines
