apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: olm-utils
  namespace: {{ .Release.Namespace }}
spec:
  params:
  - default: icr.io/cpopen/cpd/olm-utils-v2
    description: olm-utils image
    name: OLM_UTILS_IMAGE
    type: string
  - description: olm command to run
    name: OLM_CMD
    type: string
  steps:
  - image: $(params.OLM_UTILS_IMAGE)
    name: olm-run-cmd
    script: |
      oc whoami --show-server
      OCP_TOKEN=$(oc whoami -t)
      login-to-ocp --token=${OCP_TOKEN} --server=https://kubernetes.default.svc.cluster.local
      $(params.OLM_CMD)