apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: cpd-uninstall-instance
  namespace: {{ .Release.Namespace }}
spec:
  params:
    - default: icr.io/cpopen/cpd/olm-utils-v2
      description: olm-utils images
      name: OLM_UTILS_IMAGE
      type: string
    - default: 4.8.5
      description: cloud-pak for data version
      name: VERSION
      type: string
    - default: 'wml,ws'
      description: 'cloud-pak components to remove (wml,ws,watsonx_ai,watsonx_governance,watsonx_data ...)'
      name: COMPONENTS
      type: string
    - default: cpd
      description: cloud-pak operand namspace
      name: PROJECT_CPD_INST_OPERANDS
      type: string
    - default: cpd-operators
      description: cloud-pak operators namspace
      name: PROJECT_CPD_INST_OPERATORS
      type: string
    - default: ibm-cert-manager
      description: cloud-pak ibm-cert-manager namespace
      name: PROJECT_CERT_MANAGER
      type: string
    - default: ibm-licensing
      description: cloud-pak ibm-licensing namespace
      name: PROJECT_LICENSE_SERVICE
      type: string
  tasks:
    - name: components-delete-cr
      params:
        - name: OLM_UTILS_IMAGE
          value: '$(params.OLM_UTILS_IMAGE):$(params.VERSION)'
        - name: OLM_CMD
          value: |-
            delete-cr \
            --cpd_instance_ns=$(params.PROJECT_CPD_INST_OPERANDS) \
            --components=$(params.COMPONENTS) \
            --include_dependency=true
      taskRef:
        kind: Task
        name: olm-utils
      timeout: 3h0m0s
    - name: delete-olm-artifacts
      params:
        - name: OLM_UTILS_IMAGE
          value: '$(params.OLM_UTILS_IMAGE):$(params.VERSION)'
        - name: OLM_CMD
          value: |-
            delete-olm-artifacts \
            --cpd_operator_ns=$(params.PROJECT_CPD_INST_OPERANDS) \
            --delete_all_components=true
        - name: CP-INSTALL-OPTIONS
          value: cpd-install-install-option
      runAfter:
        - components-delete-cr
      taskRef:
        kind: Task
        name: olm-utils
