apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: olm-utils
  namespace: {{ .Release.Namespace }}
spec:
  params:
  - default: {{ .Values.default_olm_utils_image }}
    description: olm-utils image
    name: OLM_UTILS_IMAGE
    type: string
  - description: olm command to run
    name: OLM_CMD
    type: string
  - description: configMap which contains cloud pak install-options
    name: CP-INSTALL-OPTIONS
    type: string
    default: {{ .Release.Name }}-install-option
  - default: private-registry
    description: secret which contains credential for private registry
    name: AIRGAP-SECRET
    type: string
  steps:
  - image: $(params.OLM_UTILS_IMAGE)
    name: olm-run-cmd
    script: |
      oc whoami --show-server
      OCP_TOKEN=$(oc whoami -t)
      login-to-ocp --token=${OCP_TOKEN} --server=https://kubernetes.default.svc.cluster.local

      [ -d /opt/ansible/.airgap/secrets ] && cp ./private-registry.json /opt/ansible/.airgap/secrets/config.json

      $(params.OLM_CMD)
    volumeMounts:
      - name: "install-options"
        mountPath: /tmp/install-options/install-options.yml
        subPath: install-options.yml
      {{ if ne .Values.private_registry_secret "" }}
      - name: "airgap-secret"
        mountPath: /opt/ansible/private-registry.json
        subPath: .dockerconfigjson
      {{ end }}
  volumes:
    - name: "install-options"
      configMap:
        name: "$(params.CP-INSTALL-OPTIONS)"
    {{ if ne .Values.private_registry_secret "" }}
    - name: "airgap-secret"
      secret:
        secretName: $(params.AIRGAP-SECRET)
    {{ end  }}
