{{- if .Values.tektonPatch.enabled -}}
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: tekton-patch
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install
spec:
  pipelineRef:
    name: tekton-patch
  params:
    - name: OLM_UTILS_IMAGE
      value: icr.io/cpopen/cpd/olm-utils-v2
    - name: VERSION
      value: 4.8.5
{{- end -}}
