{{- if .Values.tektonPatch.enabled -}}
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: tekton-patch
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install
spec:
  pipelineRef:
    name: tekton-patch
  params:
    - name: OLM_UTILS_IMAGE
      value: {{ .Values.default_olm_utils_image }}
    - name: VERSION
      value: {{ .Values.cpd_version }}
{{- end -}}
